'use client'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Mail, Zap, Calendar, ArrowRight, ShieldCheck, Download, Share2 } from 'lucide-react'

interface ReportData {
  type: 'DAILY' | 'WEEKLY' | 'MONTHLY'
  totalKwh: number
  totalCost: number
  peakUsage: number
  averageVoltage: number
  startDate: string
  endDate: string
}

interface ReportPreviewModalProps {
  isOpen: boolean
  onClose: () => void
  data: ReportData | null
}

export function ReportPreviewModal({ isOpen, onClose, data }: ReportPreviewModalProps) {
  if (!data) return null;

  const title = `${data.type.charAt(0) + data.type.slice(1).toLowerCase()} Energy Report`;
  const period = `${new Date(data.startDate).toLocaleDateString()} - ${new Date(data.endDate).toLocaleDateString()}`;

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/80 backdrop-blur-sm"
          />

          {/* Modal Container */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            className="relative w-full max-w-lg bg-[#0f172a] border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
          >
            {/* Header / Email Bar */}
            <div className="bg-slate-900/50 border-b border-white/5 p-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-electric-blue/20 flex items-center justify-center border border-electric-blue/30 text-electric-blue">
                  <Mail className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-white">Email Preview</h3>
                  <p className="text-[10px] text-slate-500 uppercase tracking-wider">Generated by GridSense Engine</p>
                </div>
              </div>
              <button 
                onClick={onClose}
                className="p-2 rounded-lg hover:bg-white/5 text-slate-400 transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Scrollable Content (Simulated Email Body) */}
            <div className="flex-1 overflow-y-auto bg-slate-950/50 p-6 space-y-6">
              
              {/* Email Content Container */}
              <div className="bg-white rounded-xl overflow-hidden shadow-xl border border-white/10">
                {/* Email Header Background */}
                <div className="bg-electric-blue p-6 text-center">
                  <div className="flex justify-center mb-3">
                    <Zap className="w-8 h-8 text-white fill-white/20" />
                  </div>
                  <h1 className="text-xl font-bold text-white m-0">GridSense Energy</h1>
                  <p className="text-blue-100 text-sm opacity-80">{title}</p>
                </div>

                {/* Main Content */}
                <div className="p-8">
                  <p className="text-slate-600 text-sm mb-6">
                    Hello! Here is your energy consumption summary for the period of <strong className="text-slate-900">{period}</strong>.
                  </p>

                  {/* Metrics Grid */}
                  <div className="grid grid-cols-2 gap-4 mb-8">
                    <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 text-center">
                      <span className="text-[10px] text-slate-400 uppercase font-bold block mb-1">Total Usage</span>
                      <span className="text-xl font-black text-slate-900">{data.totalKwh.toFixed(2)} <small className="font-normal text-slate-400">kWh</small></span>
                    </div>
                    <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 text-center">
                      <span className="text-[10px] text-slate-400 uppercase font-bold block mb-1">Estimated Cost</span>
                      <span className="text-xl font-black text-emerald-600">₹{data.totalCost.toFixed(2)}</span>
                    </div>
                  </div>

                  {/* Details Section */}
                  <div className="border-t border-slate-100 pt-6 space-y-4">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Performance Insights</h4>
                    <div className="space-y-3">
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-slate-500">Peak Load Recorded</span>
                        <span className="font-semibold text-slate-800">{data.peakUsage.toFixed(0)}W</span>
                      </div>
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-slate-500">Average Grid Voltage</span>
                        <span className="font-semibold text-slate-800">{data.averageVoltage.toFixed(1)}V</span>
                      </div>
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-slate-500">Efficiency Status</span>
                        <span className="flex items-center gap-1.5 text-emerald-600 font-bold">
                          <ShieldCheck className="w-4 h-4" />
                          Optimal
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Call to Action */}
                  <div className="mt-10 text-center">
                    <button className="bg-electric-blue text-white px-8 py-3 rounded-lg font-bold text-sm shadow-lg shadow-blue-500/25 hover:scale-105 transition-all">
                      View Full Dashboard
                    </button>
                    <p className="text-[10px] text-slate-400 mt-6">
                      Sent to verified presentation address via Resend Engine.<br/>
                      © 2026 GridSense Smart Systems.
                    </p>
                  </div>
                </div>
              </div>

              {/* Action Bar (Below Email) */}
              <div className="flex gap-3">
                <button className="flex-1 flex items-center justify-center gap-2 bg-white/5 border border-white/10 py-3 rounded-xl text-slate-300 text-sm font-medium hover:bg-white/10 transition-all">
                  <Download className="w-4 h-4" />
                  Save PDF
                </button>
                <button className="flex-1 flex items-center justify-center gap-2 bg-white/5 border border-white/10 py-3 rounded-xl text-slate-300 text-sm font-medium hover:bg-white/10 transition-all">
                  <Share2 className="w-4 h-4" />
                  Forward
                </button>
              </div>

            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
